export default {
  FETCHING_PRODUCTS_SUCCESS: "FETCHING_PRODUCTS_SUCCESS",
  ADD_ENTITY: "ADD_ENTITY",
  SET_FETCH_STATE: "SET_FETCH_STATE",
  SET_ERROR_STATE: "SET_ERROR_STATE",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT"
};
